#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S3, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S4, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S2_C1_1,     fRight,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_2,     rRight,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_1,     fLeft,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     rLeft,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C1_1,     lift1,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C1_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_1,     secondStageLift, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S4_C1_2,     lift2,         tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S4_C2_1,    servo1,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S4_C2_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S4_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S4_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S4_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S4_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

int deadzone = 10;
int lift1Speed = 60;
int lift2Speed = 60;
const int lift2Default = 60;
int tubeLatchRetracted = 20;
int tubeLatchActive = 120;

bool pseudoJoyVals = false;
bool speedReleased = true;

float fLeftVal;
float fRightVal;
float rLeftVal;
float rRightVal;

float pseudofLeftVal;
float pseudofRightVal;
float pseudorLeftVal;
float pseudorRightVal;

float dampenerStrength = 0.3;

int joy1y1;
int joy1x1;
int joy1y2;
int joy1x2;
int joy2y1;
int joy2y2;

int lift1State;
int lift2State;

bool dampener;
bool rampDeployed = false;
bool tubeLatchState = false;

int max;

int maxMotorVal;

void servoInit()
{

}

void resetWheelVars()
{
	fLeftVal = 0;
	fRightVal = 0;
	rLeftVal = 0;
	rRightVal = 0;
}

void grabJoyVars()
{
	if(!pseudoJoyVals)
	{
		joy1y1 = joystick.joy1_y1;
		joy1y2 = joystick.joy1_y2;
		joy1x1 = joystick.joy1_x1;
		joy1x2 = joystick.joy1_x2;
		joy2y1 = joystick.joy2_y1;
		joy2y2 = joystick.joy2_y2;

		if(joy1Btn(6) == 1)
		{
			dampener = true;
		}
		else
		{
			dampener = false;
		}

		if(joy2Btn(5) == 1)
		{
			lift1State = 1;
		}
		else
		{
			if(joy2Btn(7) == 1)
			{
				lift1State = -1;
			}
			else
			{
				lift1State = 0;
			}
		}

		if(joy2Btn(6) == 1)
		{
			lift2State = 1;
		}
		else
		{
			if(joy2Btn(8) == 1)
			{
				lift2State = -1;
			}
			else
			{
				lift2State = 0;
			}
		}

		if(joy2Btn(2) == 1)
		{
			tubeLatchState = true;
		}

		if(joy2Btn(3) == 1)
		{
			tubeLatchState = false;
		}

		if(joy2Btn(11) == 1)
		{
			lift2Speed = lift2Default;
		}

		if(joy2Btn(1) == 1)
		{
			if(speedReleased)
			{
				lift2Speed -= 5;
			}
			speedReleased = false;
		}

		if(joy2Btn(4) == 1)
		{
			if(speedReleased)
			{
				lift2Speed += 5;
			}
			speedReleased = false;
		}

		if(joy2Btn(1) == 0 && joy2Btn(4) == 0)
		{
			speedReleased = true;
		}

		if(joy2y1 > deadzone)
		{
			rampDeployed = true;
		}

		if(joy2y1 < -deadzone)
		{
			rampDeployed = false;
		}
	}
}

void calculateMecanum()
{
	if(abs(joy1y1) > deadzone)
	{
		fLeftVal += joy1y1;
		fRightVal += joy1y1;
		rLeftVal += joy1y1;
		rRightVal += joy1y1;
	}

	if(abs(joy1x1) > deadzone)
	{
		fLeftVal -= joy1x1;
		fRightVal += joy1x1;
		rLeftVal += joy1x1;
		rRightVal -= joy1x1;
	}

	if(abs(joy1x2) > deadzone)
	{
		fLeftVal -= joy1x2;
		fRightVal += joy1x2;
		rLeftVal -= joy1x2;
		rRightVal += joy1x2;
	}
}

int maxOfFour(int num1, int num2, int num3, int num4)
{
	//int max;

	max = 0;

	if(abs(num1) >= max)
	{
		max = abs(num1);
	}

	if(abs(num2) >= max)
	{
		max = abs(num2);
	}

	if(abs(num3) >= max)
	{
		max = abs(num3);
	}

	if(abs(num4) >= max)
	{
		max = abs(num4);
	}

	return max;
}

void scaleMotorVals()
{
	maxMotorVal = maxOfFour(fRightVal, fLeftVal, rLeftVal, rRightVal);

	if(abs(maxMotorVal) > 100)
	{
		fLeftVal /= maxMotorVal;
		fRightVal /= maxMotorVal;
		rLeftVal /= maxMotorVal;
		rRightVal /= maxMotorVal;

		fLeftVal *= 100;
		fRightVal *= 100;
		rLeftVal *= 100;
		rRightVal *= 100;
	}
}

void dampen()
{
	if(dampener)
	{
		fLeftVal *= dampenerStrength;
		fRightVal *= dampenerStrength;
		rLeftVal *= dampenerStrength;
		rRightVal *= dampenerStrength;
	}
}

void setMotors()
{
	motor[fLeft] = fLeftVal;
	motor[fRight] = fRightVal;
	motor[rLeft] = rLeftVal;
	motor[rRight] = rRightVal;

	motor[lift1] = lift1Speed * lift1State;

	motor[lift2] = lift2Speed * lift2State;

	if(abs(joy2y2) >= deadzone)
	{
		motor[secondStageLift] = joy2y2;
	}
	else
	{
		motor[secondStageLift] = 0;
	}

	if(rampDeployed)
	{
		servo[servo1] = 256;
		servo[servo2] = 0;
	}
	else
	{
		servo[servo1] = 0;
		servo[servo2] = 256;
	}

	if(tubeLatchState)
	{
		servo[servo6] = tubeLatchActive;
	}
	else
	{
		servo[servo6] = tubeLatchRetracted;
	}
}

task main()
{
	waitForStart();

	servoInit();

	while(true)
	{
		alive();

		resetWheelVars();


		grabJoyVars();


		calculateMecanum();


		scaleMotorVals();

		dampen();

		pseudofLeftVal = fLeftVal;
		pseudofRightVal = fRightVal;
		pseudorLeftVal = rLeftVal;
		pseudorRightVal = rRightVal;

		setMotors();
	}
}
